# Generated by Django 2.1.15 on 2020-07-25 13:09

from django.db import migrations, models
import django_resized.forms
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[100, 100], upload_to=users.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, choices=[('Mvita', 'Mvita'), ('Kisauni', 'Kisauni'), ('Nyali', 'Nyali'), ('Changamwe', 'Changamwe'), ('Jomvu', 'Jomvu'), ('Likoni', 'Likoni')], max_length=32),
        ),
    ]
