# Generated by Django 2.1.15 on 2020-07-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200725_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
