# Generated by Django 2.1.15 on 2020-06-30 13:32

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_no',
            field=models.CharField(blank=True, default=application.models.increment_application_number, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='project_sector',
            field=models.CharField(choices=[('ENTERTAINMENT', 'Entertainment'), ('HEALTHCARE', 'Healthcare'), ('SPORTS', 'Sports'), ('ENVIRONMENT', 'Environment'), ('ECONOMIC', 'Economic')], max_length=32),
        ),
    ]
