# Generated by Django 2.1.15 on 2020-06-30 13:32

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200630_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_no',
            field=models.CharField(blank=True, default=application.models.increment_application_number, max_length=7, null=True),
        ),
    ]
