# Generated by Django 2.1.15 on 2020-07-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20200630_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='project_description',
            field=models.CharField(max_length=1500),
        ),
    ]
