# Generated by Django 2.1.15 on 2020-07-31 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_auto_20200731_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='template_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.SMSTemplate'),
        ),
    ]
