# Generated by Django 2.1.15 on 2020-07-31 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_sms_template_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='template_id',
        ),
    ]
