# Generated by Django 2.1.15 on 2020-07-23 19:47

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=13)),
                ('id_number', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('subcounty', models.CharField(choices=[('Mvita', 'Mvita'), ('Kisauni', 'Kisauni'), ('Nyali', 'Nyali'), ('Changamwe', 'Changamwe'), ('Jomvu', 'Jomvu'), ('Likoni', 'Likoni')], max_length=32)),
                ('project_name', models.CharField(max_length=128)),
                ('project_description', models.CharField(max_length=1500)),
                ('project_sector', models.CharField(choices=[('Technology', 'Technology and Innovation'), ('Art', 'Creativity and Art'), ('Healthcare', 'Promotion of Health'), ('Sports', 'Sports'), ('Environment', 'Environment'), ('Community', 'Community')], max_length=32)),
                ('people_impacted', models.IntegerField()),
                ('application_no', models.CharField(blank=True, default=application.models.increment_application_number, editable=False, max_length=7, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=32)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-application_no'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('mobile_number', 'id_number', 'application_no')},
        ),
    ]
